-- Script SQL para crear la tabla lista_compras en Supabase (PostgreSQL)

CREATE TABLE IF NOT EXISTS public.lista_compras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_chat_id BIGINT NOT NULL,
    producto TEXT NOT NULL,
    comprado BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índice para optimizar consultas por usuario / chat de Telegram
CREATE INDEX IF NOT EXISTS idx_lista_compras_chat_id ON public.lista_compras(telegram_chat_id);
