-- Script SQL para crear la tabla gastos en Supabase (PostgreSQL)

CREATE TABLE IF NOT EXISTS public.gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_chat_id BIGINT NOT NULL,
    gasto TEXT NOT NULL,
    valor NUMERIC(12, 2) NOT NULL,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para optimizar búsquedas por chat, gasto y rango de fechas
CREATE INDEX IF NOT EXISTS idx_gastos_chat_id ON public.gastos(telegram_chat_id);
CREATE INDEX IF NOT EXISTS idx_gastos_fecha ON public.gastos(fecha);
CREATE INDEX IF NOT EXISTS idx_gastos_gasto ON public.gastos(gasto);
